# Generated by Django 2.2.16 on 2022-05-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
    ]
