# Generated by Django 2.2.16 on 2022-05-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220515_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='create',
        ),
    ]
